import { useMemo, useState, type ReactNode } from 'react';
import { LanguageContext, type LanguageContextValue } from './language-context';

export type Language = 'en' | 'nl';

const copy: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    accounts: 'Accounts',
    investments: 'Investments',
    creditCards: 'Credit Cards',
    services: 'Services',
    settings: 'Settings',
    overview: 'Overview',
    financialClarity: 'Financial clarity',
    yourWorld: 'Your world',
    search: 'Search your dashboard',
    notifications: 'Notifications',
    logout: 'Log out',
    premiumMember: 'Premium Member',
    seeAll: 'See all',
    viewAll: 'View all',
    viewDetails: 'View details',
    send: 'Send',
    save: 'Save changes',
    previous: 'Previous',
    next: 'Next',
    download: 'Download',
    language: 'Language',
    profile: 'Edit profile',
    preferences: 'Preferences',
    security: 'Security',
    cardDetails: 'Card details',
    comingSoon: 'This action is ready for the next connected account.',
    transferInitiated: 'Transfer initiated successfully.',
    receiptDownloaded: 'Receipt download started.',
    settingsOpened: 'Settings opened.',
    languageChanged: 'Language changed to English.',
    viewAllReady: 'Everything is already visible in this workspace.',
    serviceListReady: 'The full service list is already visible.',
    searchReady: 'Search is ready for',
    cardActionReady: 'ready to configure.',
    monthlyChange: 'vs last month',
    myCards: 'My cards',
    recentTransactions: 'Recent transactions',
    weeklyActivity: 'Weekly activity',
    expenseStatistics: 'Expense statistics',
    quickTransfer: 'Quick transfer',
    savingsGoal: 'Savings goal',
    balanceHistory: 'Balance history',
    amount: 'Amount',
    transferTo: 'Transfer to',
    invalidAmount: 'Enter a valid amount.',
    allTransactions: 'All transactions',
    income: 'Income',
    expense: 'Expenses',
    monthExpense: 'Spent this month',
    description: 'Description',
    transactionId: 'Transaction ID',
    type: 'Type',
    card: 'Card',
    date: 'Date',
    amountLabel: 'Amount',
    receipt: 'Receipt',
    myBalance: 'My balance',
    totalSaving: 'Total savings',
    thisMonth: 'This month',
    yourAccounts: 'Your accounts',
    myCard: 'My card',
    lastTransactions: 'Latest transactions',
    debitCredit: 'Debit & credit',
    invoicesSent: 'Invoices sent',
    'cat.income': 'Income',
    'cat.transfer': 'Transfer',
    'cat.service': 'Service',
    'cat.shopping': 'Shopping',
    'cat.food': 'Groceries',
    'cat.transport': 'Transport',
    totalInvested: 'Total invested',
    numberOfHoldings: 'Positions',
    diversified: 'Diversified portfolio',
    avgReturn: 'Average return',
    thisYear: 'Year to date',
    portfolioGrowth: 'Portfolio growth',
    monthlyRevenue: 'Monthly yield',
    myHoldings: 'My holdings',
    watchlist: 'Watchlist',
    cardType: 'Card type',
    network: 'Network',
    cardNumber: 'Card number',
    holder: 'Card holder',
    nameOnCard: 'Name on card',
    expirationDate: 'Expiration date',
    addCard: 'Add card',
    addNewCard: 'Add new card',
    addCardDescription: 'Request an extra Xabi World card for private or business spending.',
    cardAdded: 'Card request received.',
    cardList: 'Card list',
    cardExpenseSplit: 'Card spending split',
    cardSettings: 'Card settings',
    blockCard: 'Block card',
    blockCardDescription: 'Instantly block your card',
    changePin: 'Change PIN',
    changePinDescription: 'Choose a new PIN code',
    addToGooglePay: 'Add to Google Pay',
    addToApplePay: 'Add to Apple Pay',
    walletDescription: 'Pay without a physical card',
    freezeCard: 'Freeze card',
    freezeDescription: 'Temporarily pause spending',
    total: 'Total',
    bankServices: 'Bank services',
    selfService: 'Fully self-service',
    secureSetup: 'Secure onboarding',
    support247: '24/7 support',
    serviceInfo: 'information opens in the connected portal.',
    integrations: 'Integrations',
    integrationsSubtitle: 'Connect Quantum Initium products to your Xabi account.',
    connected: 'Connected',
    integrationConnected: 'connected.',
    integrationDisconnected: 'disconnected.',
    descSpontiva: 'Share your Xabi profile with Spontiva for shared payments.',
    descBoostplug: 'Link Boostplug for business boost and ad payments.',
    descWoningVry: 'Link WoningVry for rent and housing payments.',
    descVvc: 'Connect VVC services to your Xabi account.',
    descDjobba: 'Link Djobba for salary and gig payments.',
    firstName: 'First name',
    lastName: 'Last name',
    phone: 'Phone number',
    dateOfBirth: 'Date of birth',
    address: 'Address',
    city: 'City',
    postalCode: 'Postal code',
    country: 'Country',
    currency: 'Currency',
    timeZone: 'Time zone',
    notifyTransactions: 'Notify me about transactions',
    notifyMerchant: 'Notify me about merchant orders',
    notifyRecommendations: 'Notify me about account recommendations',
    profileSaved: 'Profile saved successfully.',
    preferencesSaved: 'Preferences saved successfully.',
    securitySaved: 'Security settings updated.',
    twoFactor: 'Two-factor authentication',
    twoFactorDescription: 'Enable or disable two-factor authentication',
    changePassword: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    newPasswordPlaceholder: 'Enter a new password',
  },
  nl: {
    dashboard: 'Dashboard',
    transactions: 'Transacties',
    accounts: 'Rekeningen',
    investments: 'Investeringen',
    creditCards: 'Creditcards',
    services: 'Diensten',
    settings: 'Instellingen',
    overview: 'Overzicht',
    financialClarity: 'Financiële helderheid',
    yourWorld: 'Jouw wereld',
    search: 'Zoek in je dashboard',
    notifications: 'Meldingen',
    logout: 'Uitloggen',
    premiumMember: 'Premium member',
    seeAll: 'Bekijk alles',
    viewAll: 'Alles bekijken',
    viewDetails: 'Details bekijken',
    send: 'Versturen',
    save: 'Wijzigingen opslaan',
    previous: 'Vorige',
    next: 'Volgende',
    download: 'Downloaden',
    language: 'Taal',
    profile: 'Profiel bewerken',
    preferences: 'Voorkeuren',
    security: 'Beveiliging',
    cardDetails: 'Kaartdetails',
    comingSoon: 'Deze actie is klaar voor een volgende gekoppelde rekening.',
    transferInitiated: 'Overboeking gestart.',
    receiptDownloaded: 'Download van bon gestart.',
    settingsOpened: 'Instellingen geopend.',
    languageChanged: 'Taal gewijzigd naar Nederlands.',
    viewAllReady: 'Alles is al zichtbaar in deze omgeving.',
    serviceListReady: 'De volledige dienstenlijst is al zichtbaar.',
    searchReady: 'Zoeken is klaar voor',
    cardActionReady: 'klaar om in te stellen.',
    monthlyChange: 'vs vorige maand',
    myCards: 'Mijn kaarten',
    recentTransactions: 'Recente transacties',
    weeklyActivity: 'Weekactiviteit',
    expenseStatistics: 'Uitgavenstatistiek',
    quickTransfer: 'Snel overboeken',
    savingsGoal: 'Spaardoel',
    balanceHistory: 'Saldo­ontwikkeling',
    amount: 'Bedrag',
    transferTo: 'Overboeken naar',
    invalidAmount: 'Voer een geldig bedrag in.',
    allTransactions: 'Alle transacties',
    income: 'Inkomsten',
    expense: 'Uitgaven',
    monthExpense: 'Uitgegeven deze maand',
    description: 'Omschrijving',
    transactionId: 'Transactienummer',
    type: 'Type',
    card: 'Kaart',
    date: 'Datum',
    amountLabel: 'Bedrag',
    receipt: 'Bon',
    myBalance: 'Mijn saldo',
    totalSaving: 'Totaal gespaard',
    thisMonth: 'Deze maand',
    yourAccounts: 'Jouw rekeningen',
    myCard: 'Mijn kaart',
    lastTransactions: 'Laatste transacties',
    debitCredit: 'Debet & credit',
    invoicesSent: 'Verzonden facturen',
    'cat.income': 'Inkomsten',
    'cat.transfer': 'Overboeking',
    'cat.service': 'Dienst',
    'cat.shopping': 'Winkelen',
    'cat.food': 'Boodschappen',
    'cat.transport': 'Vervoer',
    totalInvested: 'Totaal belegd',
    numberOfHoldings: 'Posities',
    diversified: 'Gespreide portefeuille',
    avgReturn: 'Gemiddeld rendement',
    thisYear: 'Jaar tot nu toe',
    portfolioGrowth: 'Portefeuillegroei',
    monthlyRevenue: 'Maandelijkse opbrengst',
    myHoldings: 'Mijn posities',
    watchlist: 'Volglijst',
    cardType: 'Kaarttype',
    network: 'Netwerk',
    cardNumber: 'Kaartnummer',
    holder: 'Kaarthouder',
    nameOnCard: 'Naam op kaart',
    expirationDate: 'Vervaldatum',
    addCard: 'Kaart toevoegen',
    addNewCard: 'Nieuwe kaart aanvragen',
    addCardDescription: 'Vraag een extra Xabi World-kaart aan voor privé- of zakelijke uitgaven.',
    cardAdded: 'Kaartaanvraag ontvangen.',
    cardList: 'Kaartenlijst',
    cardExpenseSplit: 'Kaartuitgavenverdeling',
    cardSettings: 'Kaartinstellingen',
    blockCard: 'Kaart blokkeren',
    blockCardDescription: 'Blokkeer je kaart direct',
    changePin: 'PIN wijzigen',
    changePinDescription: 'Kies een nieuwe pincode',
    addToGooglePay: 'Toevoegen aan Google Pay',
    addToApplePay: 'Toevoegen aan Apple Pay',
    walletDescription: 'Betaal zonder fysieke kaart',
    freezeCard: 'Kaart bevriezen',
    freezeDescription: 'Pauzeer uitgaven tijdelijk',
    total: 'Totaal',
    bankServices: 'Bankdiensten',
    selfService: 'Volledig self-service',
    secureSetup: 'Veilige onboarding',
    support247: '24/7 support',
    serviceInfo: 'informatie opent in het gekoppelde portaal.',
    integrations: 'Integraties',
    integrationsSubtitle: 'Koppel Quantum Initium-producten aan je Xabi-account.',
    connected: 'Gekoppeld',
    integrationConnected: 'gekoppeld.',
    integrationDisconnected: 'ontkoppeld.',
    descSpontiva: 'Deel je Xabi-profiel met Spontiva voor gedeelde betalingen.',
    descBoostplug: 'Koppel Boostplug voor zakelijke boost- en advertentiebetalingen.',
    descWoningVry: 'Koppel WoningVry voor huur- en woningbetalingen.',
    descVvc: 'Koppel VVC-diensten aan je Xabi-account.',
    descDjobba: 'Koppel Djobba voor salaris- en opdrachtbetalingen.',
    firstName: 'Voornaam',
    lastName: 'Achternaam',
    phone: 'Telefoonnummer',
    dateOfBirth: 'Geboortedatum',
    address: 'Adres',
    city: 'Plaats',
    postalCode: 'Postcode',
    country: 'Land',
    currency: 'Valuta',
    timeZone: 'Tijdzone',
    notifyTransactions: 'Melding bij transacties',
    notifyMerchant: 'Melding bij handelsorders',
    notifyRecommendations: 'Melding bij account-aanbevelingen',
    profileSaved: 'Profiel opgeslagen.',
    preferencesSaved: 'Voorkeuren opgeslagen.',
    securitySaved: 'Beveiligingsinstellingen bijgewerkt.',
    twoFactor: 'Twee-factor-authenticatie',
    twoFactorDescription: 'Schakel twee-factor-authenticatie in of uit',
    changePassword: 'Wachtwoord wijzigen',
    currentPassword: 'Huidig wachtwoord',
    newPassword: 'Nieuw wachtwoord',
    newPasswordPlaceholder: 'Voer een nieuw wachtwoord in',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(
    () => (localStorage.getItem('xabi-language') as Language) || 'nl',
  );

  const setLanguage = (nextLanguage: Language) => {
    setLanguageState(nextLanguage);
    localStorage.setItem('xabi-language', nextLanguage);
  };

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      toggleLanguage: () => setLanguage(language === 'nl' ? 'en' : 'nl'),
      t: (key, fallback) => copy[language][key] || fallback || key,
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
